# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Baby Sleep' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'SnapKit'
pod 'lottie-ios' 
pod 'Firebase/Analytics'
pod 'Firebase/Database'

  # Pods for Baby Sleep

end

# Lottie - (3.1.8)

# Firebase (6.29.0)
# FirebaseAnalytics (6.7.0)
# FirebaseCore (6.9.2)
# FirebaseCoreDiagnostics (1.5.0)
# FirebaseInstallations (1.5.0)
# GoogleAppMeasurement (6.7.0)
# GoogleDataTransport (7.1.0)
# GoogleUtilities (6.7.1)
# PromisesObjC (1.2.9)
# nanopb (1.30905.0)
# FirebaseDatabase (6.4.0)
# leveldb-library (1.22)
